Repository excaliburjs/Excalibur, pull requests merged in 2018-10, with the labels that each got.

#1045 [#1043] Fix iOS 11 loading by including proper polyfills
  CHANGELOG.md
  src/engine/Engine.ts
  src/engine/Polyfill.ts
  src/engine/Resources/Sound/AudioContext.ts
Labels: bug

#1035 [#1031] Implement play game start button
  .vscode/settings.json
  CHANGELOG.md
  package-lock.json
  package.json
  sandbox/tests/animation/animation.ts
  src/engine/Engine.ts
  src/engine/Interfaces/ILoader.ts
  src/engine/Loader.css
  src/engine/Loader.logo.png
  src/engine/Loader.ts
  src/engine/UIActor.ts
  src/engine/Util/WebAudio.ts
  src/engine/files.d.ts
  src/spec/TestUtils.ts
  tslint/tslint.json
  webpack.config.js
Labels: api change, bug

#1046 [#1044] Fix iOS pointer events, include down + defense
  CHANGELOG.md
  src/engine/Input/Pointer.ts
  src/spec/PointerInputSpec.ts
Labels: bug

#1054 [chore] Add docs contribution info to README
  README.md
Labels: docs
