Repository excaliburjs/Excalibur, pull requests merged in 2018-05, with the labels that each got.

#987 [chore] [docs] Fix breakout ball collision step
  docs/source/quickstart.rst
Labels: docs

#972 [chore] Update CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: docs

#971 [#912] Add stopping PointerEvent from propagating
  CHANGELOG.md
  package-lock.json
  package.json
  sandbox/html/index.html
  sandbox/tests/input/pointer.ts
  sandbox/tests/zoom/zoom.ts
  src/engine/Actor.ts
  src/engine/Events.ts
  src/engine/Input/Pointer.ts
  src/engine/Scene.ts
  src/engine/Traits/CapturePointer.ts
  src/spec/ActorSpec.ts
  src/spec/Mocks.ts
Labels: enhancement, work-in-progress

#992 [#705] Allow setting a global anchor default for Actors
  CHANGELOG.md
  src/engine/Actor.ts
  src/engine/Index.ts
  src/spec/ActorSpec.ts
Labels: work-in-progress

#985 [#981] Fix scene remove should kill actor
  CHANGELOG.md
  src/engine/Actor.ts
  src/engine/Scene.ts
  src/spec/ActorSpec.ts
  src/spec/SceneSpec.ts
Labels: bug, work-in-progress

#983 [#982] Implement isCurrentScene convenience method
  CHANGELOG.md
  src/engine/Scene.ts
  src/spec/SceneSpec.ts
Labels: enhancement, work-in-progress
