Repository excaliburjs/Excalibur, pull requests merged in 2018-06, with the labels that each got.

#993 [#598] Expose native audio events
  CHANGELOG.md
  sandbox/tests/audio/index.html
  sandbox/tests/audio/index.ts
  src/engine/Events/MediaEvents.ts
  src/engine/Index.ts
  src/engine/Interfaces/IAudio.ts
  src/engine/Interfaces/IAudioImplementation.ts
  src/engine/Loader.ts
  src/engine/Resources/Index.ts
  src/engine/Resources/Resource.ts
  src/engine/Resources/Sound.ts
  src/engine/Resources/Sound/AudioContext.ts
  src/engine/Resources/Sound/AudioInstance.ts
  src/engine/Resources/Sound/Index.ts
  src/engine/Resources/Sound/Sound.ts
  src/engine/Util/Sound.ts
  src/engine/Util/Util.ts
  src/engine/Util/WebAudio.ts
  src/spec/SoundSpec.ts
  src/spec/Stubs.ts
Labels: work-in-progress

#988 [#884] Add prettier
  GruntFile.js
  README.md
  package-lock.json
  package.json
  prettier.config.js
  src/spec/EngineSpec.ts
  src/spec/jasmine.d.ts
Labels: tools, work-in-progress

#1007 Clarify PR template new/updated tests requirement
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs

#1004 [#1006] Fix ex.Vector.isValid Infinity edge case
  CHANGELOG.md
  src/engine/Algebra.ts
  src/spec/AlgebraSpec.ts
Labels: work-in-progress

#1011 Standardize changelog heading formatting
  CHANGELOG.md
Labels: docs

#1013 Change version to 0.0.1 for older npms?
  package.json
Labels: tools

#1014 Make contributing document friendlier
  .github/CONTRIBUTING.md
Labels: docs
