Repository excaliburjs/Excalibur, pull requests merged in 2019-11, with the labels that each got.

#1273 [#839] Change Timer implementation to support multiple handlers
  sandbox/src/game.ts
  sandbox/tests/kill/kill.ts
  src/engine/Timer.ts
  src/spec/CollisionSpec.ts
  src/spec/SceneSpec.ts
  src/spec/TimerSpec.ts
Labels: Hacktoberfest

#1323 [#1092] Add draggable getter/setter
  src/engine/Actor.ts
Labels: community in-progress, enhancement, work-in-progress

#1314 Fix typos
  STYLEGUIDE.md
  sandbox/tests/pointer/index.html
  src/engine/Actions/ActionContext.ts
  src/engine/Actor.ts
  src/engine/Algebra.ts
  src/engine/Camera.ts
  src/engine/Collision/Body.ts
  src/engine/Collision/Circle.ts
  src/engine/Collision/ClosestLineJumpTable.ts
  src/engine/Collision/Collider.ts
  src/engine/Collision/CollisionContact.ts
  src/engine/Collision/CollisionGroupManager.ts
  src/engine/Collision/CollisionShape.ts
  src/engine/Collision/CollisionType.ts
  src/engine/Collision/ConvexPolygon.ts
  src/engine/Collision/DynamicTree.ts
  src/engine/Collision/DynamicTreeCollisionBroadphase.ts
  src/engine/Collision/Pair.ts
  src/engine/Debug.ts
  src/engine/Docs/Gamepads.md
  src/engine/Docs/Physics.md
  src/engine/Docs/Pointers.md
  src/engine/Drawing/Color.ts
  src/engine/Drawing/SpriteSheet.ts
  src/engine/Engine.ts
  src/engine/EventDispatcher.ts
  src/engine/Input/Pointer.ts
  src/engine/Label.ts
  src/engine/Math/PerlinNoise.ts
  src/engine/Math/Random.ts
  src/engine/Physics.ts
  src/engine/PostProcessing/ColorBlindCorrector.ts
  src/engine/Promises.ts
  src/engine/Resources/Resource.ts
  src/engine/Resources/Sound/AudioInstance.ts
  src/engine/Scene.ts
  src/engine/Util/CullingBox.ts
  src/engine/index.ts
  src/spec/ActorSpec.ts
  src/spec/AlgebraSpec.ts
  src/spec/CameraSpec.ts
  src/spec/CollectionSpec.ts
  src/spec/CollisionContactSpec.ts
  src/spec/CollisionShapeSpec.ts
  src/spec/EasingFunctionSpec.ts
  src/spec/EngineSpec.ts
  src/spec/GroupSpec.ts
  src/spec/RandomSpec.ts
  src/spec/SceneSpec.ts
  src/spec/SortedListSpec.ts
Labels: work-in-progress

#1339 [chore] Update @obsolete's for v0.24.0
  sandbox/src/game.ts
  sandbox/tests/boundingbox/bbtester.ts
  sandbox/tests/camera/zoom.ts
  sandbox/tests/collision/index.ts
  sandbox/tests/collision/passive.ts
  sandbox/tests/collision/touching.ts
  sandbox/tests/debug/stats.ts
  sandbox/tests/group/group.ts
  sandbox/tests/input/gamepad.ts
  sandbox/tests/physics/fastphysics.ts
  sandbox/tests/physics/physics.ts
  sandbox/tests/physics/physics2.ts
  sandbox/tests/scale/scale.ts
  sandbox/tests/scene/display-mode-position.ts
  sandbox/tests/trigger/trigger.ts
  src/engine/Actions/Action.ts
  src/engine/Actor.ts
  src/engine/Algebra.ts
  src/engine/Camera.ts
  src/engine/Collision/Body.ts
  src/engine/Collision/BoundingBox.ts
  src/engine/Collision/Circle.ts
  src/engine/Collision/CollisionShape.ts
  src/engine/Collision/ConvexPolygon.ts
  src/engine/Collision/DynamicTreeCollisionBroadphase.ts
  src/engine/Collision/Edge.ts
  src/engine/Deprecated.ts
  src/engine/Drawing/Color.ts
  src/engine/Group.ts
  src/engine/Label.ts
  src/engine/Particles.ts
  src/engine/Physics.ts
  src/engine/Scene.ts
  src/engine/ScreenElement.ts
  src/engine/TileMap.ts
  src/engine/Util/EasingFunctions.ts
  src/engine/Util/Util.ts
  src/engine/index.ts
  src/spec/ActorSpec.ts
  src/spec/AlgebraSpec.ts
  src/spec/BoundingBoxSpec.ts
  src/spec/CollisionContactSpec.ts
  src/spec/CollisionShapeSpec.ts
  src/spec/FrameStatsSpec.ts
  src/spec/GroupSpec.ts
  src/spec/LabelSpec.ts
  src/spec/LogSpec.ts
  src/spec/ScaleSpec.ts
  src/spec/UtilSpec.ts
  src/spec/util/TestUtils.ts
Labels: chore
