Repository excaliburjs/Excalibur, pull requests merged in 2019-02, with the labels that each got.

#1098 [chore] Update changelog for 0.21.0 release
  CHANGELOG.md
Labels: chore

#1099 [#1078] Fix issue with offscreen culling on left side of screen
  src/engine/Camera.ts
  src/spec/SceneSpec.ts
Labels: bug

#1100 [#1096] Add flag to IEngineOptions to set canvas transparency
  CHANGELOG.md
  package-lock.json
  src/engine/Engine.ts
  src/spec/EngineSpec.ts
  src/spec/util/TestUtils.ts
Labels: enhancement
