Repository excaliburjs/Excalibur, pull requests merged in 2019-04, with the labels that each got.

#1114 [chore] Remove BaseCamera
  CHANGELOG.md
  src/engine/Camera.ts
Labels: api change

#1115 [chore] Update changelog for 0.22.0 release
  CHANGELOG.md
Labels: chore

#1133 [#1132] Guarantee polyfill application
  CHANGELOG.md
  src/engine/Engine.ts
  src/engine/Polyfill.ts
  src/engine/index.ts
Labels: bug, priority 1
