Repository excaliburjs/Excalibur, pull requests merged in 2019-05, with the labels that each got.

#1139 [chore] Remove ex references
  src/engine/Resources/Gif.ts
Labels: chore

#1135 [docs] Add Collision Type matrix
  src/engine/Docs/Physics.md
Labels: docs

#1142 Clarify issue tags and language
  .github/CONTRIBUTING.md
Labels: chore

#1148 [#1147] Make event handlers strict null/function check compatible
  CHANGELOG.md
  src/engine/Actor.ts
  src/engine/Camera.ts
  src/engine/Class.ts
  src/engine/Engine.ts
  src/engine/EventDispatcher.ts
  src/engine/Events.ts
  src/engine/Group.ts
  src/engine/Input/Gamepad.ts
  src/engine/Input/Keyboard.ts
  src/engine/Input/Pointer.ts
  src/engine/Interfaces/Evented.ts
  src/engine/Interfaces/LifecycleEvents.ts
  src/engine/Interfaces/PointerEvents.ts
  src/engine/Scene.ts
  src/engine/TileMap.ts
Labels: api change, bug

#1155 [#1152] Fix play button z-index to be reasonably above everything else
  src/engine/Loader.css
Labels: bug

#1154 [#1153] Fix no button mapping problem
  CHANGELOG.md
  src/engine/Input/Pointer.ts
Labels: bug
