Repository excaliburjs/Excalibur, pull requests merged in 2019-10, with the labels that each got.

#1268 [chore] README: Remove bower
  README.md
Labels: chore

#1217 [#1212] Switch TSlint to ESlint
  .eslintrc.js
  .vscode/extensions.json
  .vscode/settings.json
  GruntFile.js
  package-lock.json
  package.json
  src/engine/Actor.ts
  src/engine/Collision/ClosestLineJumpTable.ts
  src/engine/Collision/Collider.ts
  src/engine/Collision/CollisionJumpTable.ts
  src/engine/Configurable.ts
  src/engine/Drawing/Sprite.ts
  src/engine/Drawing/SpriteSheet.ts
  src/engine/Engine.ts
  src/engine/Label.ts
  src/engine/PostProcessing/ColorBlindCorrector.ts
  src/engine/Util/Detector.ts
  src/engine/Util/Log.ts
  src/engine/index.ts
  src/engine/tsconfig.json
  src/spec/BoundingBoxSpec.ts
  src/spec/SpriteFontSpec.ts
  src/spec/SpriteSheetSpec.ts
  src/spec/_boot.ts
  src/spec/util/Mocks.ts
  src/spec/util/Stubs.ts
Labels: work-in-progress

#1279 [#875] If the opacity of an Actor's drawing/color is 0, don't draw the actor
  CHANGELOG.md
  src/engine/Actor.ts
  src/spec/ActorSpec.ts
Labels: Hacktoberfest

#1272 Rename UIActor to ScreenActor
  sandbox/src/game.ts
  sandbox/tests/debug/stats.ts
  sandbox/tests/input/pointer.ts
  sandbox/tests/ui/index.ts
  src/engine/Engine.ts
  src/engine/Input/Pointer.ts
  src/engine/Physics.ts
  src/engine/Scene.ts
  src/engine/ScreenElement.ts
  src/engine/Util/Actors.ts
  src/engine/index.ts
  src/spec/ScaleSpec.ts
  src/spec/SceneSpec.ts
  src/spec/ScreenElementSpec.ts
  src/spec/images/ScreenElementSpec/actordoesnotdraw.png
  src/spec/images/ScreenElementSpec/actordraws.png
  src/spec/images/ScreenElementSpec/emptyctor.png
Labels: Hacktoberfest

#1278 Cleaned up code and tests removing .extends() in Class.ts to resolve Issue #1276
  CHANGELOG.md
  src/engine/Class.ts
  src/spec/ClassSpec.ts
Labels: Hacktoberfest

#1285 [#1214] Switch to core-js polyfills
  .vscode/settings.json
  CHANGELOG.md
  GruntFile.js
  karma.conf.js
  package-lock.json
  package.json
  src/engine/Polyfill.ts
  src/spec/ActionSpec.ts
  src/spec/ActorSpec.ts
  src/spec/AlgebraSpec.ts
  src/spec/AnimationSpec.ts
  src/spec/BoundingBoxSpec.ts
  src/spec/BrowserEventsSpec.ts
  src/spec/CameraSpec.ts
  src/spec/CollectionSpec.ts
  src/spec/CollisionContactSpec.ts
  src/spec/CollisionGroupSpec.ts
  src/spec/CollisionShapeSpec.ts
  src/spec/CollisionSpec.ts
  src/spec/ColorSpec.ts
  src/spec/DecoratorSpec.ts
  src/spec/DynamicTreeBroadphaseSpec.ts
  src/spec/EasingFunctionSpec.ts
  src/spec/EngineSpec.ts
  src/spec/EventSpec.ts
  src/spec/FrameStatsSpec.ts
  src/spec/GamepadSpec.ts
  src/spec/GifSpec.ts
  src/spec/GroupSpec.ts
  src/spec/KeyInputSpec.ts
  src/spec/LabelSpec.ts
  src/spec/LogSpec.ts
  src/spec/MathSpec.ts
  src/spec/ParticleSpec.ts
  src/spec/PerlinSpec.ts
  src/spec/PointerInputSpec.ts
  src/spec/PromiseSpec.ts
  src/spec/RandomSpec.ts
  src/spec/ResourceSpec.ts
  src/spec/ScaleSpec.ts
  src/spec/SceneSpec.ts
  src/spec/ScreenElementSpec.ts
  src/spec/SortedListSpec.ts
  src/spec/SoundSpec.ts
  src/spec/SpriteFontSpec.ts
  src/spec/SpriteSheetSpec.ts
  src/spec/SpriteSpec.ts
  src/spec/TileMapSpec.ts
  src/spec/TimerSpec.ts
  src/spec/TimescalingSpec.ts
  src/spec/TriggerSpec.ts
  src/spec/UtilSpec.ts
  src/spec/WebAudioInstanceSpec.ts
  src/spec/tsconfig.json
  src/spec/util/Mocks.ts
  src/spec/util/TestUtils.ts
  tsconfig.json
Labels: core team, enhancement, tech debt, tools

#1248 [chore] Tests: Migrate visual tests to Storybook
  .storybook/addons.js
  .storybook/config.js
  .storybook/webpack.config.js
  .travis.yml
  GruntFile.js
  package-lock.json
  package.json
  sandbox/index.html
  sandbox/tests/actions/fade.html
  sandbox/tests/actions/fade.ts
  sandbox/tests/animation/animation.html
  sandbox/tests/animation/animation.ts
  src/engine/Engine.ts
  src/engine/tsconfig.json
  src/stories/Actions.stories.ts
  src/stories/Animations.stories.ts
  src/stories/assets/animation.png
  src/stories/assets/heart.png
  src/stories/globals.d.ts
  src/stories/tsconfig.json
  src/stories/utils.ts
Labels: chore, core team, enhancement

#1300 [#1299] Fix non-vector backed camera position
  CHANGELOG.md
  src/engine/Camera.ts
  src/spec/CameraSpec.ts
Labels: bug

#1271 [chore] Actions: Label PRs from branch names
  .github/pr-labeler.yml
  .github/workflows/pr-labeler.yml
Labels: chore, core team

#1311 Travis: Don't require GH_TOKEN when building a fork
  version.js
Labels: bug, chore, tools

#1303 [chore] stories: Migrate anchor visual tests
  sandbox/tests/anchors/anchors.ts
  sandbox/tests/anchors/index.html
  src/stories/Transforms.anchors.stories.ts
Labels: chore, core team

#1315 [chore] Renovate on certain days
  renovate.json
Labels: chore
