Repository excaliburjs/Excalibur, pull requests merged in 2020-04, with the labels that each got.

#1475 [chore] Refactor for build speed
  .gitignore
  Excalibur.sublime-project
  GruntFile.js
  README.md
  apidocs.js
  appveyor.yml
  package-lock.json
  package.json
  sandbox/tsconfig.json
  src/engine/tsconfig.json
  webpack.config.js
  webpack.config.prod.js
Labels: chore

#1485 chore(Storybook): Add build-storybook step and deployment
  .gitignore
  .storybook/main.js
  .storybook/webpack.config.js
  .travis.yml
  package-lock.json
  package.json
Labels: chore, core team, tools

#1474 feat(Sound): Add duration and processed event, visual test migration
  CHANGELOG.md
  package-lock.json
  package.json
  sandbox/index.html
  sandbox/tests/audio/index.html
  sandbox/tests/audio/index.ts
  sandbox/tests/audio/longsound.html
  sandbox/tests/audio/longsound.ts
  sandbox/tests/audio/setvolume.html
  sandbox/tests/audio/setvolume.ts
  src/engine/Events/MediaEvents.ts
  src/engine/Resources/Sound/AudioInstance.ts
  src/engine/Resources/Sound/Sound.ts
  src/engine/files.d.ts
  src/spec/SoundSpec.ts
  src/stories/Audio.stories.ts
  src/stories/assets/loop-campfire.mp3
  src/stories/assets/loop-forest.mp3
  src/stories/assets/loop-guitar.mp3
  src/stories/utils.ts
  webpack.config.js
Labels: bug, chore, enhancement

#1499 [chore] Update changelog for 0.24.0 release
  CHANGELOG.md
Labels: chore

#1511 fix(Keyboard): Fix accessing cross-origin frame exception
  .storybook/manager.js
  CHANGELOG.md
  src/engine/Input/Keyboard.ts
  src/stories/Actions.stories.ts
  src/stories/Anchors.stories.ts
  src/stories/Keyboard.stories.ts
  src/stories/Pointers.stories.ts
  src/stories/utils.ts
Labels: bug, fix
