Repository excaliburjs/Excalibur, pull requests merged in 2020-05, with the labels that each got.

#1532 [chore]: Add more action stories
  src/stories/Actions.stories.ts
Labels: chore

#1534 [chore] Add actions intro story and split rotate story
  src/stories/Actions.stories.ts
Labels: chore

#1540 chore: [#1508] Update Renovate/release commit format
  release.js
  renovate.json
Labels: tools

#1537 docs: Streamline language in the readme
  README.md
Labels: docs

#1544 chore: Upgrade to TypeScript 3.9.2
  CHANGELOG.md
  package-lock.json
  package.json
  src/engine/Debug.ts
  src/engine/Input/Pointers.ts
Labels: chore

#1545 chore: Update to node 12
  .nvmrc
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore

#1551 chore: Switch to lint-staged
  .prettierignore
  package-lock.json
  package.json
  src/engine/Docs/Groups.md
  src/spec/ActorSpec.ts
Labels: chore, tools

#1507 fix: [#1417] [#1431] Loader positioning, allow customization, clean-up html
  CHANGELOG.md
  package.json
  src/engine/Loader.ts
  src/spec/LoaderSpec.ts
  src/spec/images/LoaderSpec/100.png
  src/spec/images/LoaderSpec/fifty.png
  src/spec/images/LoaderSpec/loader-position-color.png
  src/spec/images/LoaderSpec/logo-position.png
  src/spec/images/LoaderSpec/playbuttonshown-noprogressbar.png
  src/spec/images/LoaderSpec/zero.png
Labels: enhancement, fix
