Repository excaliburjs/Excalibur, pull requests merged in 2020-10, with the labels that each got.

#1671 docs(readme): fix a typo
  README.md
Labels: community in-progress, docs

#1677 fix: Make engine parameter optional for scene constructor
  CHANGELOG.md
  src/engine/Scene.ts
Labels: Hacktoberfest

#1672 docs: Update documented usage for label constructor
  src/engine/Docs/Labels.md
  src/engine/Label.ts
Labels: Hacktoberfest, community in-progress, docs

#1670 feat: [#1670] Add key code enums and KeyboardEvent.code support
  sandbox/tests/zoom/zoom.ts
  src/engine/Input/Keyboard.ts
  src/spec/KeyInputSpec.ts
  src/stories/Keyboard.stories.ts
Labels: Hacktoberfest, community in-progress

#1674 feat: [#1673] Implement Feature Flags
  CHANGELOG.md
  src/engine/Engine.ts
  src/engine/Flags.ts
  src/engine/index.ts
  src/spec/FlagsSpec.ts
Labels: enhancement, feature
