Repository excaliburjs/Excalibur, pull requests merged in 2021-11, with the labels that each got.

#2072 feat: [#2044] Add Current Graphics Keys to GraphicsComponent
  CHANGELOG.md
  src/engine/Graphics/GraphicsComponent.ts
  src/spec/GraphicsComponentSpec.ts
Labels: hacktoberfest-accepted

#2101 docs: Clarify contribution requirements
  .github/CONTRIBUTING.md
Labels: docs

#2071 refactor: Pointer System refactor
  .eslintrc.json
  CHANGELOG.md
  sandbox/src/game.ts
  sandbox/tests/boundingbox/bbtester.ts
  sandbox/tests/input/pointer.ts
  sandbox/tests/physics/physics.ts
  src/engine/Actor.ts
  src/engine/Class.ts
  src/engine/Engine.ts
  src/engine/Events/ExEvent.ts
  src/engine/Events/PointerEvents.ts
  src/engine/Input/EngineInput.ts
  src/engine/Input/Index.ts
  src/engine/Input/NativePointerButton.ts
  src/engine/Input/Pointer.ts
  src/engine/Input/PointerAbstraction.ts
  src/engine/Input/PointerButton.ts
  src/engine/Input/PointerComponent.ts
  src/engine/Input/PointerEvent.ts
  src/engine/Input/PointerEventReceiver.ts
  src/engine/Input/PointerEvents.ts
  src/engine/Input/PointerScope.ts
  src/engine/Input/PointerSystem.ts
  src/engine/Input/PointerType.ts
  src/engine/Input/Pointers.ts
  src/engine/Input/WheelDeltaMode.ts
  src/engine/Input/WheelEvent.ts
  src/engine/Interfaces/PointerEventHandlers.ts
  src/engine/Scene.ts
  src/engine/ScreenElement.ts
  src/engine/Traits/CapturePointer.ts
  src/engine/Traits/Index.ts
  src/engine/index.ts
  src/spec/ActorSpec.ts
  src/spec/PointerInputSpec.ts
  src/spec/util/Mocks.ts
  src/stories/Audio.stories.ts
  src/stories/Pointers.stories.ts
Labels: hacktoberfest-accepted

#2103 Refactor: Remove .call() in EventDispatcher
  CHANGELOG.md
  src/engine/Class.ts
  src/engine/Collision/BodyComponent.ts
  src/engine/Collision/ColliderComponent.ts
  src/engine/Collision/Colliders/Collider.ts
  src/engine/EventDispatcher.ts
  src/engine/Graphics/Animation.ts
  src/engine/Input/PointerAbstraction.ts
  src/engine/Resources/Resource.ts
  src/engine/Trigger.ts
  src/spec/CollisionSpec.ts
  src/spec/EventSpec.ts
Labels: hacktoberfest-accepted

#2104 fix: Arcade Solver Jitter on stacked/overlapped tiles
  CHANGELOG.md
  src/engine/Collision/Solver/ArcadeSolver.ts
  src/spec/ArcadeSolverSpec.ts
Labels: bug

#2107 fix: [#2106] Safari 13.1 Does not boot + Safari Pointers
  .github/workflows/browsersupport.yml
  CHANGELOG.md
  karma.conf.browsers.js
  package-lock.json
  package.json
  sandbox/tests/pointer/index.html
  sandbox/tests/screen/index.html
  src/browsersupport/BrowserSupportSpec.ts
  src/browsersupport/tsconfig.json
  src/engine/Input/PointerEventReceiver.ts
  src/engine/Screen.ts
Labels: bug

#2108 docs: Remove TravisCI badge
  README.md
Labels: docs

#2122 feat: [#577] [#1170] Implement new Clock API
  CHANGELOG.md
  sandbox/src/game.ts
  src/engine/Debug/Debug.ts
  src/engine/Engine.ts
  src/engine/EntityComponentSystem/SystemManager.ts
  src/engine/Loader.ts
  src/engine/Scene.ts
  src/engine/Util/Clock.ts
  src/engine/Util/Fps.ts
  src/engine/Util/Util.ts
  src/engine/Util/WebAudio.ts
  src/engine/index.ts
  src/engine/tsconfig.json
  src/spec/ActionSpec.ts
  src/spec/ActorSpec.ts
  src/spec/ClockSpec.ts
  src/spec/CollisionShapeSpec.ts
  src/spec/CollisionSpec.ts
  src/spec/ColorBlindCorrectorSpec.ts
  src/spec/DebugSystemSpec.ts
  src/spec/EngineSpec.ts
  src/spec/FrameStatsSpec.ts
  src/spec/LoaderSpec.ts
  src/spec/ParticleSpec.ts
  src/spec/PointerInputSpec.ts
  src/spec/ResourceSpec.ts
  src/spec/ScaleSpec.ts
  src/spec/SceneSpec.ts
  src/spec/ScreenElementSpec.ts
  src/spec/TileMapSpec.ts
  src/spec/TimescalingSpec.ts
  src/spec/TriggerSpec.ts
  src/spec/util/TestUtils.ts
  wallaby.js
Labels: enhancement

#2131 fix: Prevent pair generation for composite colliders
  CHANGELOG.md
  src/engine/Collision/Detection/DynamicTreeCollisionProcessor.ts
  src/engine/Collision/Detection/Pair.ts
  src/engine/Loader.ts
  src/spec/CollisionSpec.ts
  src/spec/DynamicTreeBroadphaseSpec.ts
  src/spec/PairSpec.ts
Labels: bug
