Repository excaliburjs/Excalibur, pull requests merged in 2021-01, with the labels that each got.

#1735 feat: [#1733][#1734] New FullScreen and Dynamic DisplayModes
  CHANGELOG.md
  sandbox/html/index.html
  sandbox/src/game.ts
  src/engine/Algebra.ts
  src/engine/Input/Pointers.ts
  src/engine/Screen.ts
  src/engine/TileMap.ts
  src/spec/ScreenSpec.ts
Labels: enhancement, feature

#1753 chore: switch deploy-docs script to Octokit instead of Travis
  deploy-docs.js
  package-lock.json
  package.json
Labels: chore, core team

#1752 chore: Switch to GH actions
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .travis.yml
  GruntFile.js
  apidocs.js
  package-lock.json
  package.json
  release.js
  version.js
Labels: chore, core team

#1756 feat: Rename FullScreen -> Fit, Dynamic -> Fill
  CHANGELOG.md
  sandbox/src/game.ts
  src/engine/Engine.ts
  src/engine/Screen.ts
  src/spec/ScreenSpec.ts
Labels: enhancement
