Repository excaliburjs/Excalibur, pull requests merged in 2021-12, with the labels that each got.

#2142 feat: Post Processing Improvements + Pre-multiplied alpha
  CHANGELOG.md
  sandbox/src/game.ts
  src/engine/Debug/DebugFlags.ts
  src/engine/Engine.ts
  src/engine/Graphics/Context/ExcaliburGraphicsContext.ts
  src/engine/Graphics/Context/ExcaliburGraphicsContext2DCanvas.ts
  src/engine/Graphics/Context/ExcaliburGraphicsContextWebGL.ts
  src/engine/Graphics/Context/render-source.ts
  src/engine/Graphics/Context/render-target.ts
  src/engine/Graphics/Context/screen-renderer.ts
  src/engine/Graphics/Context/shader.ts
  src/engine/Graphics/Context/shaders/point-fragment.glsl
  src/engine/Graphics/Context/shaders/screen-fragment.glsl
  src/engine/Graphics/Context/shaders/screen-vertex.glsl
  src/engine/Graphics/Context/texture-loader.ts
  src/engine/Graphics/PostProcessor/ColorBlindnessMode.ts
  src/engine/Graphics/PostProcessor/ColorBlindnessPostProcessor.ts
  src/engine/Graphics/PostProcessor/PostProcessor.ts
  src/engine/Graphics/PostProcessor/color-blind-fragment.glsl
  src/engine/Graphics/index.ts
  src/engine/PostProcessing/ColorBlindCorrector.ts
  src/engine/PostProcessing/Index.ts
  src/engine/PostProcessing/PostProcessor.ts
  src/engine/index.ts
  src/spec/ColorBlindCorrectorSpec.ts
  src/spec/ParticleSpec.ts
  src/spec/images/ParticleSpec/Particles.png
Labels: enhancement

#2160 fix(tsconfig): restrict types array
  src/engine/globals.d.ts
  src/engine/index.ts
  src/engine/tsconfig.json
Labels: bug

#2168 feat: Support image filtering modes on ImageSource & Raster Graphics
  CHANGELOG.md
  sandbox/src/game.ts
  sandbox/tests/gif/animatedGif.ts
  src/engine/Engine.ts
  src/engine/Graphics/Circle.ts
  src/engine/Graphics/Context/texture-loader.ts
  src/engine/Graphics/Filtering.ts
  src/engine/Graphics/Font.ts
  src/engine/Graphics/Graphic.ts
  src/engine/Graphics/ImageSource.ts
  src/engine/Graphics/Polygon.ts
  src/engine/Graphics/Raster.ts
  src/engine/Graphics/index.ts
  src/engine/Label.ts
  src/engine/Loader.ts
  src/spec/EngineSpec.ts
  src/spec/GraphicsCircleSpec.ts
  src/spec/GraphicsImageSourceSpec.ts
  src/spec/GraphicsPolygonSpec.ts
  src/spec/GraphicsTextSpec.ts
Labels: enhancement

#2169 feat: Fixes and updates to support `@excaliburjs/dev-tools`
  CHANGELOG.md
  sandbox/datgui/dat.gui.js
  sandbox/excalibur-dev-tools/dev-tools.d.ts
  sandbox/excalibur-dev-tools/dev-tools.js
  sandbox/html/healthbar.tmpl
  sandbox/html/index.html
  sandbox/src/game.ts
  sandbox/tests/physics/index.html
  sandbox/tests/physics/physics.ts
  src/engine/Actor.ts
  src/engine/Camera.ts
  src/engine/Debug/DebugSystem.ts
  src/engine/Engine.ts
  src/engine/Graphics/Context/ExcaliburGraphicsContext.ts
  src/engine/Graphics/Context/ExcaliburGraphicsContext2DCanvas.ts
  src/engine/Graphics/Context/ExcaliburGraphicsContextWebGL.ts
  src/engine/Graphics/Context/shaders/image-fragment.glsl
  src/engine/Graphics/Context/shaders/point-fragment.glsl
  src/engine/Graphics/DebugGraphicsComponent.ts
  src/engine/Graphics/Raster.ts
  src/engine/Graphics/Sprite.ts
  src/engine/Graphics/index.ts
  src/engine/Input/PointerEventReceiver.ts
  src/engine/Input/PointerSystem.ts
  src/engine/Label.ts
  src/engine/Math/matrix.ts
  src/engine/Scene.ts
  src/engine/Screen.ts
  src/engine/TileMap.ts
  src/engine/index.ts
  src/spec/DebugSystemSpec.ts
  src/spec/ExcaliburGraphicsContextSpec.ts
  src/spec/GraphicsSpriteSpec.ts
  src/spec/LabelSpec.ts
  src/spec/MatrixSpec.ts
  src/spec/PointerInputSpec.ts
  src/spec/SceneSpec.ts
  src/spec/ScreenSpec.ts
  src/spec/images/DebugSystemSpec/debug-draw-component.png
  src/spec/images/DebugSystemSpec/tilemap-debug.png
  src/spec/images/ExcaliburGraphicsContextSpec/webgl-circle-with-opacity.png
  src/spec/images/GraphicsSpriteSpec/change-size-and-scale.png
Labels: enhancement, work-in-progress
