Repository excaliburjs/Excalibur, pull requests merged in 2024-07, with the labels that each got.

#3120 fix: [#3119] Fix graphics type + apply strictness to Graphics types
  CHANGELOG.md
  src/engine/Graphics/Animation.ts
  src/engine/Graphics/Context/ExcaliburGraphicsContext.ts
  src/engine/Graphics/Context/ExcaliburGraphicsContext2DCanvas.ts
  src/engine/Graphics/Context/ExcaliburGraphicsContextWebGL.ts
  src/engine/Graphics/Context/circle-renderer/circle-renderer.ts
  src/engine/Graphics/Context/debug-text.ts
  src/engine/Graphics/Context/draw-call.ts
  src/engine/Graphics/Context/image-renderer/image-renderer.ts
  src/engine/Graphics/Context/line-renderer/line-renderer.ts
  src/engine/Graphics/Context/material-renderer/material-renderer.ts
  src/engine/Graphics/Context/material.ts
  src/engine/Graphics/Context/point-renderer/point-renderer.ts
  src/engine/Graphics/Context/quad-index-buffer.ts
  src/engine/Graphics/Context/rectangle-renderer/rectangle-renderer.ts
  src/engine/Graphics/Context/render-target.ts
  src/engine/Graphics/Context/shader.ts
  src/engine/Graphics/Context/state-stack.ts
  src/engine/Graphics/Context/texture-loader.ts
  src/engine/Graphics/Context/transform-stack.ts
  src/engine/Graphics/Context/vertex-buffer.ts
  src/engine/Graphics/Context/vertex-layout.ts
  src/engine/Graphics/Context/webgl-util.ts
  src/engine/Graphics/Filtering.ts
  src/engine/Graphics/Font.ts
  src/engine/Graphics/FontCache.ts
  src/engine/Graphics/FontTextInstance.ts
  src/engine/Graphics/Graphic.ts
  src/engine/Graphics/GraphicsComponent.ts
  src/engine/Graphics/GraphicsSystem.ts
  src/engine/Graphics/ImageSource.ts
  src/engine/Graphics/OffscreenSystem.ts
  src/engine/Graphics/Polygon.ts
  src/engine/Graphics/PostProcessor/ColorBlindnessPostProcessor.ts
  src/engine/Graphics/Raster.ts
  src/engine/Graphics/SpriteFont.ts
  src/engine/Graphics/Text.ts
  src/engine/Graphics/tsconfig.json
Labels: bug

#3122 feat: add CollisionContact.bias(collider)
  CHANGELOG.md
  src/engine/Collision/Detection/CollisionContact.ts
  src/spec/CollisionContactSpec.ts
Labels: enhancement

#3124 fix: rewrite ClosestLine and PolygonPolygonClosestLine logic for improved accuracy on sloped polygons
  src/engine/Collision/Colliders/ClosestLineJumpTable.ts
  src/spec/CollisionShapeSpec.ts
Labels: bug

#3127 fix: [#3126] Fix keyboard events in scene scope
  CHANGELOG.md
  package-lock.json
  sandbox/tests/scene-keyboard/index.html
  sandbox/tests/scene-keyboard/index.ts
  src/engine/Director/Director.ts
  src/engine/Input/InputHost.ts
  src/engine/Input/Keyboard.ts
Labels: bug

#2974 feat: WebGLTexture garbage collection
  CHANGELOG.md
  sandbox/tests/memory-leaker/index.html
  sandbox/tests/memory-leaker/index.ts
  src/engine/Engine.ts
  src/engine/GarbageCollector.ts
  src/engine/Graphics/Context/ExcaliburGraphicsContextWebGL.ts
  src/engine/Graphics/Context/texture-loader.ts
  src/engine/index.ts
  src/spec/GarbageCollectorSpec.ts
Labels: enhancement

#3129 chore: Upgrade docusaurus to 3.4.0 + new patch
  site/docs/02-fundamentals/03-actors.mdx
  site/docs/02-fundamentals/04-architecture.mdx
  site/docs/02-fundamentals/04-scenes.mdx
  site/docs/04-graphics/04.4-graphics-context.mdx
  site/docusaurus.config.ts
  site/old-patches/@docusaurus+core+3.0.0.patch
  site/package-lock.json
  site/package.json
  site/patches/@docusaurus+core+3.4.0.patch
  site/sidebars.ts
  src/engine/Actions/ActionContext.ts
Labels: docs, chore

#3133 fix: [#3128] Unused scene loader locks up engine
  CHANGELOG.md
  sandbox/tests/loader-lockup/index.html
  sandbox/tests/loader-lockup/index.ts
  src/engine/Director/DefaultLoader.ts
  src/spec/DefaultLoaderSpec.ts
Labels: bug

#3138 fix: Emitter pool was created whether you used it or not
  src/engine/EntityComponentSystem/Entity.ts
  src/engine/Particles/ParticleEmitter.ts
  src/engine/Particles/Particles.ts
Labels: bug

#3136 feat: Implement Collision Sub-Stepping
  sandbox/tests/high-gravity-arcade/index.html
  sandbox/tests/high-gravity-arcade/index.ts
  src/engine/Collision/Colliders/CollisionJumpTable.ts
  src/engine/Collision/CollisionSystem.ts
  src/engine/Collision/Index.ts
  src/engine/Collision/MotionSystem.ts
  src/engine/Collision/PhysicsConfig.ts
  src/engine/Collision/Solver/ArcadeSolver.ts
  src/spec/CollisionContactSpec.ts
Labels: enhancement
