Repository excaliburjs/Excalibur, pull requests merged in 2024-10, with the labels that each got.

#3232 docs(events): Fuller example with pub/sub
  site/docs/02-fundamentals/04-events.mdx
Labels: docs, hacktoberfest-accepted

#3239 feat: Add alias fixed update timestep
  src/engine/Camera.ts
  src/engine/Engine.ts
  src/engine/Graphics/GraphicsSystem.ts
Labels: enhancement

#3244 feat: [#150] Implement SVG support in ImageSource with static builder
  CHANGELOG.md
  karma.conf.js
  sandbox/images/arrows.svg
  sandbox/src/game.ts
  src/engine/Graphics/ImageSource.ts
  src/engine/Graphics/Sprite.ts
  src/spec/ImageSourceSpec.ts
  src/spec/images/GraphicsImageSourceSpec/arrows.svg
  wallaby.js
Labels: enhancement

#3235 fix: [#3087] `blockInput: true` blocks input accessors
  CHANGELOG.md
  src/engine/Input/Keyboard.ts
  src/engine/Input/PointerEventReceiver.ts
Labels: bug

#3248 feat: Add Slide Transition
  CHANGELOG.md
  karma.conf.js
  sandbox/src/game.ts
  src/engine/Collision/Colliders/CircleCollider.ts
  src/engine/Collision/PhysicsConfig.ts
  src/engine/Director/CrossFade.ts
  src/engine/Director/DefaultLoader.ts
  src/engine/Director/Director.ts
  src/engine/Director/FadeInOut.ts
  src/engine/Director/Loader.ts
  src/engine/Director/Slide.ts
  src/engine/Director/Transition.ts
  src/engine/Director/index.ts
  src/engine/Director/tsconfig.json
  src/engine/Engine.ts
  src/engine/EntityComponentSystem/EntityManager.ts
  src/engine/Graphics/GraphicsComponent.ts
  src/engine/Graphics/OffscreenSystem.ts
  src/engine/Util/Coroutine.ts
  src/engine/Util/DrawUtil.ts
  src/engine/Util/EasingFunctions.ts
  src/spec/ActorSpec.ts
  src/spec/ArcadeSolverSpec.ts
  src/spec/CollisionShapeSpec.ts
  src/spec/CollisionSpec.ts
  src/spec/DirectorSpec.ts
  src/spec/EngineSpec.ts
  src/spec/SceneSpec.ts
  src/spec/SlideSpec.ts
  src/spec/TransistionSpec.ts
  src/spec/_boot.ts
  src/spec/images/SlideSpec/slide-down.png
  src/spec/images/SlideSpec/slide-left.png
  src/spec/images/SlideSpec/slide-right.png
  src/spec/images/SlideSpec/slide-up-transition.png
  src/spec/images/SlideSpec/slide-up.png
  src/spec/util/TestUtils.ts
Labels: enhancement

#3238 fix: [#3098] Make collision events consistent targets
  CHANGELOG.md
  sandbox/src/game.ts
  sandbox/tests/collision/touching.ts
  sandbox/tests/high-gravity-arcade/index.ts
  site/docs/00-your-first-game.mdx
  src/engine/Collision/ColliderComponent.ts
  src/engine/Events.ts
  src/engine/Trigger.ts
  src/spec/CollisionSpec.ts
Labels: bug

#3255 fix: [#3250] Stop cancelled pointer events from bubbling to the top level
  CHANGELOG.md
  src/engine/Input/PointerEventReceiver.ts
  src/spec/PointerInputSpec.ts
Labels: bug
